FROM golang:1.20-alpine

RUN apk update && apk add --no-cache nodejs npm curl

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin && \
    cd local && npm i && npm i -g serverless
