version: "3.5"

services:
  dynamodb:
    image: "amazon/dynamodb-local:1.21.0"
    container_name: dynamodb
    working_dir: /home/dynamodblocal
    volumes:
      - "./local/docker/dynamodb/data:/home/dynamodblocal/data"
    ports:
      - 8000:8000
    environment:
      - AWS_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_SESSION_TOKEN=local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
