name: Deploy chat-live domain

on:
  push:
    branches:
      - main
    paths:
      - chat-live/**

jobs:
  build_chat_live:
    name: build_chat_live
    uses: ./.github/workflows/call-jenkins.yml
    with:
      DOMAIN: chat-live
    secrets:
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_CHAT_LIVE_TOKEN }}
      IMAGE_VERSION: ${GITHUB_SHA::7}
