name: Deploy chat domain

on:
  push:
    branches:
      - main
    paths:
      - chat/**

jobs:
  build_chat:
    name: build_chat
    uses: ./.github/workflows/call-jenkins.yml
    with:
      DOMAIN: chat
    secrets:
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_CHAT_TOKEN }}
      IMAGE_VERSION: ${GITHUB_SHA::7}
